name: Build BurningKnight
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build BurningKnight
    runs-on: windows-2019
    steps:
      - name: Upload depots to steam
        shell: bash
        run: |
           git clone "https://${{ secrets.GITHUB_KEY }}@github.com/egordorichev/steam_builder.git"
           mkdir Linux
           mkdir Windows
           mkdir Macos
           echo "lin">>Linux/hi
           echo "win">>Windows/hi
           echo "mac">>Macos/hi
           mkdir "/Program Files (x86)/Steam/steam" -p
           cp ./steam_builder/ssfn2631791037380626867 "/Program Files (x86)/Steam/"
           cp ./steam_builder/ssfn2631791037380626867 "/Program Files (x86)/Steam/steam/"
           ls -l "/Program Files (x86)/Steam/steam/"
           mkdir "/Program Files/Steam/steam" -p
           cp ./steam_builder/ssfn2631791037380626867 "/Program Files/Steam/"
           cp ./steam_builder/ssfn2631791037380626867 "/Program Files/Steam/steam/"
           ls -l "/Program Files/Steam/steam/"
           mkdir -p ./steam_builder/tools/ContentBuilder/builder/public/
           cp ./steam_builder/steambootstrapper_english.txt ./steam_builder/tools/ContentBuilder/builder/public/
           ls -l ./steam_builder/tools/ContentBuilder/builder/public/
           cd steam_builder/tools/ContentBuilder
           mkdir ./content/Windows
           cp ../../../Windows/* ./content/Windows/
           mkdir ./content/Linux
           cp ../../../Linux/* ./content/Linux/
           mkdir ./content/Macos
           cp ../../../Macos/* ./content/Macos/
           builder/steamcmd.exe +login "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" +run_app_build_http ../scripts/app_build_851150.vdf +quit
           
